"""new option fields

Revision ID: 156210c61c1b
Revises: 9fb7341bc808
Create Date: 2019-05-11 11:20:02.447858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156210c61c1b'
down_revision = '9fb7341bc808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_timestamp'), 'option', ['timestamp'], unique=False)
    op.create_table('option_user',
    sa.Column('id_option', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_option'], ['option.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_user')
    op.drop_index(op.f('ix_option_timestamp'), table_name='option')
    op.drop_table('option')
    # ### end Alembic commands ###
