"""empty message

Revision ID: 931bdefd9069
Revises: a601169b9e80
Create Date: 2019-05-11 14:46:43.704624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931bdefd9069'
down_revision = 'a601169b9e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id_option', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_option'], ['option.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.drop_table('option_user')
    op.create_foreign_key(None, 'option', 'poll', ['id_poll'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_table('option_user',
    sa.Column('id_option', sa.INTEGER(), nullable=True),
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_option'], ['option.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], )
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
