"""added new fields for poll

Revision ID: 9fb7341bc808
Revises: 542d55448ff1
Create Date: 2019-05-11 09:51:35.342120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb7341bc808'
down_revision = '542d55448ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('poll', sa.Column('title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'title')
    op.drop_column('poll', 'image_url')
    # ### end Alembic commands ###
