"""empty message

Revision ID: a601169b9e80
Revises: 156210c61c1b
Create Date: 2019-05-11 11:46:33.498732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a601169b9e80'
down_revision = '156210c61c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('id_poll', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'option', 'poll', ['id_poll'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_column('option', 'id_poll')
    # ### end Alembic commands ###
