"""empty message

Revision ID: cdcd18bb0b5f
Revises: c8d5e9ddbf33
Create Date: 2019-05-18 15:07:15.611850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcd18bb0b5f'
down_revision = 'c8d5e9ddbf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'url')
    # ### end Alembic commands ###
