"""empty message

Revision ID: f2fa96d024f2
Revises: cdcd18bb0b5f
Create Date: 2019-05-19 01:32:46.491016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa96d024f2'
down_revision = 'cdcd18bb0b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('url', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
